MNT Add update js deps workflow
silverstripe/silverstripe-campaign-admin pull request #219
Opened 2022-03-08 01:12 UTC by emteknetnz

2022-03-08 22:32 UTC, maxime-rainville requested changes

2022-03-08 22:33 UTC, maxime-rainville commented on .github/workflows/update-js-deps.yml
> +  cron: '0 0 1 */3 *'
```suggestion
    # Run on a schedule once a quarter
    cron: '0 0 1 */3 *'
```

2022-03-09 21:17 UTC, maxime-rainville approved these changes

2022-03-09 21:17 UTC, merged

2022-03-09 21:32 UTC, emteknetnz commented
:/ didn't work https://github.com/silverstripe/silverstripe-campaign-admin/actions/runs/1959741076